version: '2'
services:
  plex:
    image: linuxserver/plex
    network_mode: host
    environment:
      # Relative times displayed in the Plugin are based off this timezone
      - TZ=America/Phoenix
      - VERSION=latest
    volumes:
      - ../:/config/Library/Application Support/Plex Media Server/Plug-ins/Radarr.bundle:ro
      - ./logs:/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs

  sonarr:
    image: linuxserver/radarr
    ports:
      - "7878:7878"
    volumes:
      - /dev/rtc:/dev/rtc:ro

  nginx:
    image: nginx
    depends_on:
     - radarr
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/htpasswd:/etc/nginx/passwords:ro
